services:
  slurmnode1:
    image: slurm-node:latest
    hostname: slurmnode1
    user: admin
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    volumes:
      - /mnt/workspace:/home/admin
 #   ports:
 #     - 16818:6818
 #   depends:
 #     - slurmmaster

volumes:
  shared.vol:

networks:
  host:
    name: host
    external: true
