services:
  slurmnode3:
    image: slurm-node:latest
    hostname: slurmnode3
    container_name: slurmnode3
    user: admin
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /mnt/workspace:/home/admin
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./node/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                          
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                        
    # ports:
    #   - 6818:6818
volumes:
  shared.vol:

networks:
  host:
    name: host
    external: true
