services:
  slurmmaster:
    image: slurm-master:latest
    container_name: slurmmaster
    hostname: slurmmaster
    user: admin
    network_mode: host    
    volumes:
      - ./workspace:/home/admin
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./master/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                  
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                  
    # ports:
    #   - 6817:6817
    #   - 6819:6819
    # links:
    #   - slurmdbd
networks:
  host:
    name: host
    external: true
