services:
  mariadb:
    image: mariadb:10.10
    hostname: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/slurm-mariadb:/var/lib/mysql
    environment:
      - MARIADB_USER=slurm
      - MARIADB_PASSWORD=slurm
      - MARIADB_ROOT_PASSWORD=dbroot-password
      - MARIADB_DATABASE=slurm
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - mariadb      
  slurmdbd:
    image: slurm-dbd:latest
    hostname: slurmdbd
    user: slurm
    volumes:
      - ./workspace:/home/slurm
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./dbd/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                  
    ports:
      - 7031:7031
    links:
      - mariadb
  slurmmaster:
    image: slurm-master:latest
    hostname: slurmmaster
    user: admin
    volumes:
      - ./workspace:/home/admin
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./master/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                  
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                  
    ports:
      - 6817:6817
      - 6819:6819
    links:
      - slurmdbd
  slurmnode1:
    image: slurm-node:latest
    hostname: slurmnode1
    user: admin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./workspace:/home/admin
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./node/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                          
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                        
    ports:
      - 6818:6818
    links:
      - slurmmaster
  slurmnode2:
    image: slurm-node:latest
    hostname: slurmnode2
    user: admin
    volumes:
      - ./workspace:/home/admin
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./node/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                                
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                        
    links:
      - slurmmaster
  slurmnode3:
    image: slurm-node:latest
    hostname: slurmnode3
    user: admin
    volumes:
      - ./workspace:/home/admin
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./node/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                                
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                        
    links:
      - slurmmaster      
  slurmjupyter:
    image: slurm-jupyter:latest
    hostname: slurmjupyter
    user: admin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./workspace:/home/admin 
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./jupyter/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                                
      - /sys/fs/cgroup:/sys/fs/cgroup:ro                        
    ports:
      - 8888:8888
    links:
      - slurmmaster
volumes:
  slurm-workspace:
  slurm-mariadb:
